---
  # vim: ft=yaml sw=2 ts=2 sts=2
  extends: "eslint-config-airbnb-es5"
  rules:
    comma-dangle:
      - "warn"
      - "always-multiline"
    func-names: "off"
    no-spaced-func: "warn"
    space-before-function-paren:
      - "warn"
      - anonymous: "always"
        named: "never"
    no-underscore-dangle: "off"
...
