language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: misha@ginkgobioworks.com
  api_key:
    secure: PmhEuk/SJq8GnYmWi+ji3gi9dcEtZi3CCYCHelqViEtWNqv+PF8SK+e7sDQCzvO5erZYL7Rfvu1L9x9f3yRJ5mchDQvcXO6NakUc3QliQ2r+chy0J9Zq2oSukd217B1hbl6+bYYYZtYi4YHuo/cuB1yd7HqKDkub7rHEWkC01x+jVvGY8lX2jQCSlTb3yr8oXzohLlAGoXglomO7q1kqiySDLIJoQDLYHHcgbPYKyzPMUixxJsb9t40tfIdko+c35Kct9rfCTNzZYQkna0LjM0xTpxQQl6iy6tY1v+Xa4+n7AJxPyEnjkhMyLDKWoJGhBDRaoym33MVjt1wwPCvrzaQsHW5wFpHEwBsRATuXxfY/Wytu7HV9jOyB61aeqTJ4h29SReTdCeN/WHlOHc5nW5GbF82/N2stkPBgP1qdbLCj0Tilj0ya97mO+q1HcCIkSwAZiCb1iX48EFziHDK7Oxs1reI0qv6Zp9rGVCm0QmLmhklf4J8t4r9syY0GpP7DV6bYxf9qY7+VQDYU2RG4C3ONDezpXfQCYfMAcfFnQzGMQksdE9dbEXgZ0GcxA9sLoN6bwB06KJ3AuyiEhzsgmXP9udGILueyvObRub3N34QINoxNLk3ajhpDFzMeGzsWivmw5PqDL9584PHb67pm4ZTeU90OupSQjSxvdfRrMN0=
  on:
    tags: true
    repo: ginkgobioworks/curious-js
    branch: master
  skip_cleanup: true
